spring:
  application:
    name: dubbo_auto_configuration_consumer_demo
dubbo:
  application:
    name: dubbo_consumer
  registry:
    protocol: zookeeper
    address: zookeeper://127.0.0.1:2181
server:
  port: 9191
